language: ruby
env:
  - RAILS_ENV=test
before_install:
  # Install host application to run test with
  - cd .. && git clone --depth=50 --branch=master https://github.com/jplusplus/jquest.git jquest
  # It must use the current engine directory as base
  - bundle config local.jquest_pg  ./jquest-pg
  - bundle config disable_local_branch_check true
  # Checksum arbitrary fail: https://github.com/bundler/bundler/issues/5332
  - gem install -v 1.13.6 bundler --no-rdoc --no-ri
install:
  # Ensure we install package from host application directory
  - cd jquest
  - bundle _1.13.6_ install --jobs=3 --retry=3
script:
  - rspec
rvm:
  - 2.3.1
