language: ruby
env:
  - RAILS_ENV=test
before_install:
  # Install host application to run test with
  - cd .. && git clone --depth=50 --branch=master https://github.com/jplusplus/jquest.git jquest
  # It must use the current engine directory as base
  - bundle config local.jquest_pg  ./jquest-pg
  - bundle config disable_local_branch_check true
  # Checksum arbitrary fail: https://github.com/bundler/bundler/issues/5332
  - gem install -v 1.13.6 bundler --no-rdoc --no-ri
install:
  - cd jquest
  # Ensure we install package from host application directory
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle _1.13.6_ install --jobs=3 --retry=3
  # Disable frontend dependencies until tests apply to frontend components
  # - npm install bower
  # - bower install
script:
  - bundle exec rails db:environment:set db:drop db:create db:migrate
  - bundle exec rspec ../jquest-pg/spec
rvm:
  - 2.3.1
